export enum Antiques {
  advertising = 'Advertising',
  alcoholRelated = 'Alcohol related',
  appliances = 'Appliances',
  artDecoRetro = 'Art deco & retro',
  automotiveTransport = 'Automotive & transport',
  bottles = 'Bottles',
  clocksScientificInstruments = 'Clocks & scientific instruments',
  coins = 'Coins',
  documentsMaps = 'Documents & maps',
  foodDrink = 'Food & drink',
  furnitureWoodenware = 'Furniture & woodenware',
  jewellery = 'Jewellery',
  militaria = 'Militaria',
  movieTV = 'Movie & TV memorabilia',
  museumPiecesArtifacts = 'Museum pieces & artifacts',
  ornamentsFigurines = 'Ornaments & figurines',
  phonecards = 'Phonecards',
  pinsBadgesPatches = 'Pins, badges & patches',
  postcardsWriting = 'Postcards & writing',
  silverMetalwareTins = 'Silver, metalware & tins',
  stamps = 'Stamps',
  textilesLinen = 'Textiles & linen',
  tobacco = 'Tobacco related',
  other = 'Other'
}
