name: TradeMe.Test

env:
  PASSWORDS: testpassword=${{ secrets.TESTPASSWORD }} token=${{ secrets.TOKEN }} tokensecret=${{ secrets.TOKENSECRET }} key=${{ secrets.KEY }} keysecret=${{ secrets.KEYSECRET }}

on:
 push:
  branches:
    - '*'
 pull_request:
  branches:
    - master

jobs:
  test:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install npm packages
        run: npm ci
      - name: Lint project
        if: ${{ always() }}
        run: npm run lint
      - name: Run API tests
        if: ${{ always() }}
        run: ${{ env.PASSWORDS }} npm run api-test
      - name: Run UI tests
        if: ${{ always() }}
        run: ${{ env.PASSWORDS }} npm run ui-test
