name: TradeMe Test

env:
  PASSWORDS: testuser=${{ secrets.USERNAME }} testpassword=${{ secrets.TESTPASSWORD }} token=${{ secrets.TOKEN }} tokensecret=${{ secrets.TOKENSECRET }} key=${{ secrets.KEY }} keysecret=${{ secrets.KEYSECRET }}

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main


jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install npm packages
        run: npm ci
      - name: Lint project
        if: always()
        run: npm run lint
      - name: Run API tests
        if: always()
        run: ${{ env.PASSWORDS }} npm run test-api
      - name: Run UI tests
        if: always()
        run: ${{ env.PASSWORDS }} npm run test-ui
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'junit/*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
